print("Welcome to the tip calculator!")
bill = float(input("What was the total bill?" )) 
tip = int (input("How much tip would you like to give? 10, 12, or 15? ")) 
pipl = int (input("How many people to split the bill? "))
pay= round(((bill+(bill/100)*tip))/pipl,2)
print(f"Each person should pay:{pay} ")
